[package]
name = "schema-curd"
version = "0.1.0"
edition = "2024"
default-run = "schema-curd"

[[bin]]
name = "schema-curd-cli"
path = "src/cli.rs"

[features]
default = ["mysql"]
sqlite = ["sqlx/sqlite"]
mysql = []

[dependencies]
corers = { version = "0.1.0", path = "../../corers", features = ["axum", "jwt", "net", "time", "tracing"]}

anyhow = "1"
axum = { version = "0.8.9", features = ["macros"] }
validator = { version = "0.21", features = ["derive"] }
chrono = { version = "0.4.41", features = ["serde"] }
regex = "1.12.3"
sqlx = { version = "0.9.0", default-features = false, features = ["mysql", "mysql-rsa", "postgres", "runtime-tokio", "json", "macros", "chrono"] }
thiserror = "2.0.18"
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread", "net", "signal", "sync"] }
tracing = "0.1.44"
tracing-appender = "0.2.4"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dotenvy = "0.15.7"
envy = "0.4.2"
rexl = { version = "0.0.5", features = ["serde"] }

strum = { version = "0.28.0", features = ["derive"] }
either = { version = "1", features = ["serde", "std"] }
moka = { version = "0.12.16", features = ["future"] }
async-trait = "0.1.89"
argon2 = { version = "0.5.3", features = ["std"]}

redis = { version = "1", features = ["tokio-comp"] }
kevy-embedded = { version = "=4.1.1", default-features = false, features = ["core"] }

[dev-dependencies]
tower = { version = "0.5.3", features = ["util"] }
